### ISSUE TITLE
sdss_access reports done when it is not

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_access#2]
When running sdss_access to rsync stuff from the SAS, it reports that it is Done when it's actually still running.  This is probably ok when the number of files is small, but when downloading a whole directory that takes awhile, this can be misleading.  Users think it's done but that it didn't work when in fact the files are still downloading.

**Comment by joelbrownstein** [comment]
I am confused by how to proceed.  Do I fix it in svn, first, and then you can merge the changes into github?  Or do I need to fix it in github and then merge the changes into svn?

**Comment by albireox** [comment]
I think it's up to you. I can sync bidirectionally so you can fix it anywhere you like and I'll push the changes the other direction.

**Comment by havok2063** [comment]
Bumping this as this is still an issue.

**Comment by joelbrownstein** [comment]
This is fixed (in svn).  Please pull to git and test (added a little extra verbosity to the wait loop)
