### ISSUE TITLE
Permissions issue with rsync

### ISSUE THREAD

**Issue by imedan** [sdss/sdss_access#39]
I am running into an issue where I am trying to download some spectra from IPL-2 via rsync with sdss_access and I am getting permission errors despite having set up the ``~\.netrc`` file. When I try to run this script:

```
from sdss_access.path import Path

path = Path(release='IPL2', preserve_envvars=True)

from sdss_access import Access

access = Access(release='IPL2')

access.remote()
access.add('spAll', run2d='v6_0_9')
access.set_stream()
access.commit()
```

It asks for a password and then I get the following error after entering the password:

```
[ERROR]: Traceback (most recent call last):
  File "test_permission_error.py", line 11, in <module>
    access.set_stream()
  File "/Users/imedan/anaconda3/lib/python3.6/site-packages/sdss_access/sync/baseaccess.py", line 99, in set_stream
    self.set_stream_task(task)
  File "/Users/imedan/anaconda3/lib/python3.6/site-packages/sdss_access/sync/rsync.py", line 60, in set_stream_task
    out = self.get_task_out(task=task)
  File "/Users/imedan/anaconda3/lib/python3.6/site-packages/sdss_access/sync/rsync.py", line 37, in get_task_out
    raise AccessError("Return code %r\n%s" % (status, err))
sdss_access.path.path.AccessError: Return code 5
b'@ERROR: auth failed on module ipl-2\nrsync error: error starting client-server protocol (code 5) at main.c(1857) [Receiver=3.2.6]\n'
```

When I try to download the same file via rsync in command line:

```
rsync -avz rsync://sdss5@dtn.sdss.org/ipl-2/spectro/boss/redux/v6_0_9/spAll-v6_0_9.fits .
```

It still asks for the password, but I am able to download the data after entering it.

For reference, the line in my ``~/.netrc`` file reads:

```
machine dtn.sdss5.org login <username> password <password>
```

Any idea on what the issue may be?

**Comment by havok2063** [comment]
@joelbrownstein I think this is an issue with the rsync server and not `sdss_access`.  When I run the following 
```
rsync -avz rsync://sdss5@dtn.sdss.org/ipl-2/spectro/boss/redux/v6_0_9/spAll-v6_0_9.fits .
```
from the command-line, I get a password prompt (with MOTD), even though I have my `.netrc` file set up.

**Comment by havok2063** [comment]
@joelbrownstein is this issue fixed?

**Comment by joelbrownstein** [comment]
This issue is fixed in principle by https://github.com/sdss/sdss_access/pull/41
